# Generated by Django 4.2.1 on 2023-07-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('nationality', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('matches', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('average', models.CharField(max_length=50)),
                ('wickets', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
